---
title: "5.0-go错误处理error与defer,panic,recover" #标题
date: 2023-07-16T19:44:10+08:00 #创建时间
lastmod: 2023-07-16T19:44:10+08:00 #更新时间
author: ["citybear"] #作者
categories: # 没有分类界面可以不填写
- tech
tags: # 标签
- go面向对象
- go源码
keywords: 
- 
description: "" #描述 每个文章内容前面的展示描述
weight: # 输入1可以顶置文章，用来给文章展示排序，不填就默认按时间排序
slug: ""
draft: false # 是否为草稿
comments: true #是否展示评论 有自带的扩展成twikoo
showToc: true # 显示目录 文章侧边栏toc目录
TocOpen: true # 自动展开目录
hidemeta: false # 是否隐藏文章的元信息，如发布日期、作者等
disableShare: true # 底部不显示分享栏
showbreadcrumbs: true #顶部显示当前路径
cover:
    image: "" #图片路径：posts/tech/文章1/picture.png
    caption: "" #图片底部描述
    alt: ""
    relative: false

# reward: true # 打赏
mermaid: true #自己加的是否开启mermaid
---

# error接口
- Go 语言为错误处理定义了一个标准模式，即 <font color="red">error 接口</font>
- 通过<font color="red">**Go 标准错误包 errors**</font> 提供的 New() 方法快速创建一个<font color="red"> error 类型的错误实例</font>
- fmt.Println(err), 打印错误信息时，直接传入了 err 对象实例，因为 Go 底层会<font color="red">自动调用 err 实例上的 Error() 方法返回错误信息并将其打印出来，就像普通类的 String() 方法一样。</font>
-  <font color="red">编写代码时就已经预见并返回的</font>
``` go
type error interface { 
    Error() string 
}

// 一般这样返回错误 返回error类型
func Foo(param int) (n int, err error) { 
    // ...
    // err = errors.New("只支持非负整数相加")
}
n, err := Foo(0)

if err != nil { 
    // 错误处理 
} else {
    // 使用返回值 n 
}
```

- 可以通过 fmt.Errorf() 格式化方法返回 error 类型错误，其底层调用的其实也是 errors.New 方法
``` go
func Errorf(format string, a ...interface{}) error {
    return errors.New(Sprintf(format, a...))
}
```

# 更复杂的错误类型
## 系统内置错误类型
Go 语言内置的很多包还封装了更复杂的错误类型。扩展了特定的信息

- 以 os 包为例，这个包主要负责与操作系统打交道，所以提供了 LinkError、PathError、SyscallError 这些<font color="red">实现了 error 接口</font>的错误类型，以 PathError 为例
``` go
type PathError struct {
    Op   string
    Path string
    Err  error
}

// 错误类型除了组合 error 接口实现 Error() 方法外，
// 还提供了额外的操作类型字段 Op 和文件路径字段 Path 以丰富错误信息
func (e *PathError) Error() string { 
    return e.Op + " " + e.Path + ": " + e.Err.Error() 
}

// 获取指定路径文件信息，对应类型是 FileInfo
fi, err := os.Stat("test.txt") 
if err != nil {
    switch err.(type) {
    // 如果文件不存在，则返回 PathError 类型错误    
    case *os.PathError:
        // do something
    case *os.LinkError:
        // dome something
    case *os.SyscallError:
        // dome something
    case *exec.Error:
        // dome something
    }
} else {
    // ...
}
```

## 自定义错误类型
仿照 PathError 的实现自定义一些复杂的错误类型，**只需要<font color="red">组合 error 接口并实现 Error() 方法</font>即可，然后按照自己的需要为自定义类型添加一些属性字段**

# defer语句
Go 语言中的类没有构造函数和析构函数的概念，处理错误和异常时也没有提供 try...catch...finally 之类的语法，那当我们想要在某个资源使用完毕后将其释放（网络连接、文件句柄等），或者在代码运行过程中抛出错误时执行一段兜底逻辑

- 通过 defer 关键字<font color="red">声明兜底执行或者释放资源的语句</font>, 相当于php的析构和finally
- 一个函数/方法中可以存在多个 defer 语句, defer 语句的<font color="red">调用顺序入栈出栈</font>，执行顺序是从后往前执行
- 运行时抛出错误会中断后面代码的执行，也就**感知不到后面的 defer 语句。**
- <font color="red">调用时匿名函数时，有闭包，引用外部变量时，以当时值为准</font>, defer后面的函数在入栈的时候保存的是入栈那一刻的值，而当时x的值是10
- return之后的语句先执⾏，defer后的语句后执⾏

``` go
// 延迟执行函数defer 通常用于清理某些资源和处理某些异常
// return之后的语句先执⾏，defer后的语句后执⾏
// 在一个函数中,如果有多个 defer 那它的执行顺序是从后往前执行 入栈出栈，后期对传入参数修改，并不会影响栈内函数的值
var tmpStr string = "hello world"

// panic 程序异常中断,在go里面代表了不可修复的错误,在go中defer在panic之后也是会执行的, 但是注册在panic代码前面的财执行，且值为当时的传入值
func TestDefer(t *testing.T) {
	defer func() {
		fmt.Println("clear resources.", tmpStr)
	}()

	x := 10
	defer func(x int) {
		x++
		jbStr := "city"
		tmpStr = tmpStr + " 修改全局变量tmpStr" //
		fmt.Println(tmpStr, jbStr)

		fmt.Println("defer ", x) // 11
	}(x) //这里调用了x变量 defer后面的函数在入栈的时候保存的是入栈那一刻的值，而当时x的值是10，所以后期对x修改，并不会影响栈内函数的值

	x += 5
	fmt.Println("cur", x) // cur 15
	// x = x/0
	//panic("err") // panic后面的代码不会跑，包括后面才注册的defer
	returnAndDeferFunc()

	fmt.Println(tmpStr) // hello world 正常执行下来的

}

var testInt int

func TestOrder(t *testing.T) {
	testInt := returnAndDeferFunc()
	fmt.Println(testInt) // 输出2
}

func deferFunc() {
	fmt.Println("defer func called...")
	testInt = 1
}

func returnFunc() int {
	fmt.Println("return func called...")
	testInt = 2
	return testInt
}

// return之后的语句先执⾏，defer后的语句后执⾏
func returnAndDeferFunc() int {
	defer deferFunc()

	return returnFunc()
}

```

# panic函数
- 对于某些运行时错误，比如数组越界、除数为0、空指针引用

当代码运行时出错，而又没有在编码时显式返回错误时，Go 语言会抛出 panic，中文译作「运行时恐慌」，我们也可以将其看作 Go 语言版的异常
- 在代码中显式抛出 panic
- <font color="red">panic 函数支持的参数类型是 interface{} , func panic(v interface{})</font>
- 当遇到 panic 时，Go 语言会<font color="red">中断当前协程（即 main 函数）后续代码的执行</font>，然后执行在<font color="red">中断代码之前定义的 defer 语句</font>（按照先入后出的顺序），最后**程序退出并输出 panic 错误信息**，以及出现错误的堆栈跟踪信息
  - 第一行表示出问题的协程，
  - 第二行是问题代码所在的包和函数，
  - <font color="red">第三行是问题代码的具体位置</font>
  - 最后一行则是程序的退出状态

## panic 的传播:
  - 当一个 Goroutine 执行 panic 时,panic 会向上冒泡,传递到该 Goroutine 的调用栈顶。
  - 如果在调用栈上没有找到任何 recover() 语句,panic 会继续向外传播,直到到达该 Goroutine 的入口点。
  - <font color="red">如果该 Goroutine 是主 Goroutine,panic 会导致整个程序崩溃。</font>
  - 如果该 Goroutine 是一个非主 Goroutine,panic 会导致该 Goroutine 终止,但不会影响其他 Goroutine。

- 例子1
``` go
goroutine 554286 [running]: // 第一行
runtime.throw({0x133cbd3?, 0x12171a0?})
    /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0007f87e0 sp=0xc0007f87b0 pc=0x4382f1
runtime.mapassign_faststr(0x1141520, 0xc000bac0f0, {0x1351d36, 0x1}) // 第二行
    /usr/local/go/src/runtime/map_faststr.go:295 +0x38b fp=0xc0007f8848 sp=0xc0007f87e0 pc=0x41342b
smart-admp/internal/biz.(*DailyCostUseCase).checkTask(0xc000a13630, {0x156d478, 0xc000c6a8a0}, 0xc000efa4f0, 0xc00066ab60, 0x5?, 0xc000c6a930?, 0xc000c6b350?, 0xc000bac000?, 0xc000bac030, ...) // // 第三行 问题代码的具体位置，如果在调用栈上没有找到任何 recover() 语句,panic 会继续向外传播,直到到达该 Goroutine 的入口点。
    /builds/tuiguang/smart-admp/internal/biz/daily_cost.go:336 +0xe46 fp=0xc0007f8f70 sp=0xc0007f8848 pc=0xf83ce6
smart-admp/internal/biz.(*DailyCostUseCase).BatchCheck.func2()
    /builds/tuiguang/smart-admp/internal/biz/daily_cost.go:159 +0x65 fp=0xc0007f8fe0 sp=0xc0007f8f70 pc=0xf82805
runtime.goexit() // 第四行程序的退出状态
    /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0007f8fe8 sp=0xc0007f8fe0 pc=0x4684e1
created by smart-admp/internal/biz.(*DailyCostUseCase).BatchCheck
    /builds/tuiguang/smart-admp/internal/biz/daily_cost.go:159 +0xd7f
    
```
- 例子二
![alt text](image1.jpg)

``` go
package main

import "fmt"

func main() {
    defer func() {
        fmt.Println("代码清理逻辑")
    }()

    var i = 1
    var j = 0
    if j == 0 {
        panic("除数不能为0！")
    }
    k := i / j
    fmt.Printf("%d / %d = %d\n", i, j, k)
}
```
![](panic1.png)

# recover() 函数
通过 recover() 函数对 panic 进行捕获和处理，<font color="red">从而避免程序崩溃然后直接退出</font>，而是继续可以执行后续代码，实现类似PHP 中 try...catch 语句的功能。
- 这个 panic 的捕获应该<font color="red">放到 defer 语句中</font>完成，才可以在抛出 panic 时通过 recover 函数将其捕获，**defer 语句执行完毕后，会退出抛出 panic 的当前函数**
``` go
defer func() {
    if err := recover(); err != nil {
        fmt.Printf("Runtime panic caught: %v\n", err)
    }
}()
```
- 通过 recover() 函数<font color="red">捕获了 panic，并打印捕获到的错误信息，这个时候，程序会退出函数而不是整个应用</font>
- 调用 defer 语句声明的匿名函数，如果没有panic发生，那么recover() 函数返回值为 nil，不会执行 if 分支代码
**类比为 panic、recover、defer 组合起来实现了传统面向对象编程异常处理的 try…catch…finally 功能。**

## 使用场景
- 只有在希望在某个 Goroutine 出现 panic 时,能够优雅地恢复或处理它,而不是让整个程序崩溃时,才需要使用 recover()。
- 常见的使用场景包括:
  - 在 HTTP 服务器的处理程序中使用 recover(),以防止单个请求导致整个服务器崩溃。
  - 在长期运行的 Goroutine 中使用 recover(),以确保它们不会因为 panic 而退出。
  - 在某些关键的业务逻辑中使用 recover(),以防止局部错误导致整个系统失败。
``` go
func myHandler(w http.ResponseWriter, r *http.Request) {
    defer func() {
        if r := recover(); r != nil {
            log.Printf("Recovered from panic: %v\n%s", r, debug.Stack())
            http.Error(w, "Internal Server Error", http.StatusInternalServerError)
        }
    }()

    // 处理请求的逻辑
}
```

# Fatal
- fatal 是 log 包中的一个函数,它会打印出错误信息并立即终止程序的执行。
- fatal 函数内部实际上是调用了 os.Exit(1) 来退出程序。
- 使用 fatal 函数,程序会以非零的退出码退出,表示程序运行失败
``` go
func main() {
        host := flag.String("host", "127.0.0.1", "监听地址")
        port := flag.Int("port", 8080, "监听端口")
        appName := flag.String("name", "", "服务名")
        flag.Parse()

        if *appName == "" {
                log.Fatalln("服务名未定义")
        }

        fmt.Println(*host, *port, *appName)
}
```
## 使用场景
- fatal: 当遇到无法继续执行的严重错误时使用,比如无法连接数据库、无法打开文件等。这种情况下,程序无法继续运行,需要立即终止并反馈给调用方。
- panic: 当遇到无法预料的、程序无法继续运行的错误时使用,比如数组越界、除以零等。这种情况下,可以使用 panic 中断程序的执行,并由上层的 recover 来处理

# errors.Is和errors.As区别(官方不推荐使用 error == xxx)

- <font color="red">[Go 源码解读｜如何用好 errors 库的 errors.Is() 与 errors.As() 方法](https://juejin.cn/post/7148673417066053646)</font>

- **<font color="red">总的来说，errors.Is函数用于判断错误是否与给定类型匹配，而errors.As函数则用于将错误转换为指定类型的变量。</font>**
  - 例如，假设有一个错误链，其中包含多个错误对象，可以使用errors.Is函数来判断错误链中是否存在某个特定类型的错误，而使用errors.As函数来将错误链中的某个错误转换为指定类型的变量，以便进一步处理该错误。
- 对包装过的error依然生效

在Go语言中，errors.Is和errors.As是处理错误的两个重要函数。

errors.Is函数用于判断一个错误值是否与给定的错误类型匹配。它会递归地查找错误链中的每个错误，直到找到一个与给定类型匹配的错误，或者到达错误链的末尾。如果找到匹配的错误，errors.Is函数会返回true，否则返回false。

errors.As函数用于将错误的值转换为指定类型的变量。它会递归地查找错误链中的每个错误，直到找到一个与给定类型匹配的错误，或者到达错误链的末尾。如果找到匹配的错误，errors.As函数会将错误的值赋给指定类型的变量，并返回true，否则返回false。

这两个函数的主要区别在于它们的返回值和用途。errors.Is函数返回一个布尔值，用于判断错误是否与给定类型匹配，而errors.As函数返回一个布尔值，同时会将错误的值赋给指定类型的变量。

# 多协程的错误处理，标准库errgroup

errgroup包提供了一种方便的方式来跟踪和处理多个goroutine中的错误。它可以让你启动多个goroutine，并等待它们全部完成，或者在任何一个goroutine返回错误时立即取消所有其他goroutine。

[文章讲解](https://www.cnblogs.com/shuiche/p/17851356.html)

# 使用wrapped error来构建错误链
[要么返回错误值，要么输出日志](https://mp.weixin.qq.com/s/HvWBKN4Kk2rwHamvSTEUQQ)

- 比如: kratos在biz最顶层才封装错误，打印输出日志

# error 处理最佳实践
https://mytechshares.com/2021/11/22/go-error-best-practice/
- todo 待补充过来