---
title: "go错误处理" #标题
date: 2023-07-16T19:44:10+08:00 #创建时间
lastmod: 2023-07-16T19:44:10+08:00 #更新时间
author: ["citybear"] #作者
categories: # 没有分类界面可以不填写
- tech
tags: # 标签
- go面向对象
keywords: 
- 
description: "" #描述 每个文章内容前面的展示描述
weight: # 输入1可以顶置文章，用来给文章展示排序，不填就默认按时间排序
slug: ""
draft: false # 是否为草稿
comments: true #是否展示评论 有自带的扩展成twikoo
showToc: true # 显示目录 文章侧边栏toc目录
TocOpen: true # 自动展开目录
hidemeta: false # 是否隐藏文章的元信息，如发布日期、作者等
disableShare: true # 底部不显示分享栏
showbreadcrumbs: true #顶部显示当前路径
cover:
    image: "" #图片路径：posts/tech/文章1/picture.png
    caption: "" #图片底部描述
    alt: ""
    relative: false

# reward: true # 打赏
mermaid: true #自己加的是否开启mermaid
---

# error接口
- Go 语言为错误处理定义了一个标准模式，即 <font color="red">error 接口</font>
- 通过<font color="red">**Go 标准错误包 errors**</font> 提供的 New() 方法快速创建一个<font color="red"> error 类型的错误实例</font>
- fmt.Println(err), 打印错误信息时，直接传入了 err 对象实例，因为 Go 底层会<font color="red">自动调用 err 实例上的 Error() 方法返回错误信息并将其打印出来，就像普通类的 String() 方法一样。</font>
-  <font color="red">编写代码时就已经预见并返回的</font>
``` go
type error interface { 
    Error() string 
}

// 一般这样返回错误 返回error类型
func Foo(param int) (n int, err error) { 
    // ...
    // err = errors.New("只支持非负整数相加")
}
n, err := Foo(0)

if err != nil { 
    // 错误处理 
} else {
    // 使用返回值 n 
}
```

- 可以通过 fmt.Errorf() 格式化方法返回 error 类型错误，其底层调用的其实也是 errors.New 方法
``` go
func Errorf(format string, a ...interface{}) error {
    return errors.New(Sprintf(format, a...))
}
```

# 更复杂的错误类型
## 系统内置错误类型
Go 语言内置的很多包还封装了更复杂的错误类型。扩展了特定的信息

- 以 os 包为例，这个包主要负责与操作系统打交道，所以提供了 LinkError、PathError、SyscallError 这些<font color="red">实现了 error 接口</font>的错误类型，以 PathError 为例
``` go
type PathError struct {
    Op   string
    Path string
    Err  error
}

// 错误类型除了组合 error 接口实现 Error() 方法外，
// 还提供了额外的操作类型字段 Op 和文件路径字段 Path 以丰富错误信息
func (e *PathError) Error() string { 
    return e.Op + " " + e.Path + ": " + e.Err.Error() 
}

// 获取指定路径文件信息，对应类型是 FileInfo
fi, err := os.Stat("test.txt") 
if err != nil {
    switch err.(type) {
    // 如果文件不存在，则返回 PathError 类型错误    
    case *os.PathError:
        // do something
    case *os.LinkError:
        // dome something
    case *os.SyscallError:
        // dome something
    case *exec.Error:
        // dome something
    }
} else {
    // ...
}
```

## 自定义错误类型
仿照 PathError 的实现自定义一些复杂的错误类型，**只需要<font color="red">组合 error 接口并实现 Error() 方法</font>即可，然后按照自己的需要为自定义类型添加一些属性字段**

# defer语句
Go 语言中的类没有构造函数和析构函数的概念，处理错误和异常时也没有提供 try...catch...finally 之类的语法，那当我们想要在某个资源使用完毕后将其释放（网络连接、文件句柄等），或者在代码运行过程中抛出错误时执行一段兜底逻辑

- 通过 defer 关键字<font color="red">声明兜底执行或者释放资源的语句</font>, 相当于php的析构和finally
- 一个函数/方法中可以存在多个 defer 语句, defer 语句的<font color="red">调用顺序遵循先进后出的原则</font>
- 运行时抛出错误会中断后面代码的执行，也就**感知不到后面的 defer 语句。**
- <font color="red">调用时匿名函数时，有闭包，引用外部变量时，以当时值为准</font>
``` go
package main

import "fmt"

func printError()  {
    fmt.Println("兜底执行")
}

func main()  {
    defer printError()
    defer func() {
        fmt.Println("除数不能是0!")
    }()

    var i = 1
    var j = 1
    // var j = 0
    // 遇到除数为 0，则抛出 panic，然后立即中断当前函数 main 的执行（后续其他语句都不再执行），
    // 并按照先进后出顺序依次执行已经在当前函数中声明过的 defer 语句

    var k = i / j

    fmt.Printf("%d / %d = %d\n", i, j, k)
}
```

# panic函数
- 对于某些运行时错误，比如数组越界、除数为0、空指针引用

当代码运行时出错，而又没有在编码时显式返回错误时，Go 语言会抛出 panic，中文译作「运行时恐慌」，我们也可以将其看作 Go 语言版的异常
- 在代码中显式抛出 panic
- <font color="red">panic 函数支持的参数类型是 interface{} , func panic(v interface{})</font>
- 当遇到 panic 时，Go 语言会<font color="red">中断当前协程（即 main 函数）后续代码的执行</font>，然后执行在<font color="red">中断代码之前定义的 defer 语句</font>（按照先入后出的顺序），最后**程序退出并输出 panic 错误信息**，以及出现错误的堆栈跟踪信息
  - 第一行表示出问题的协程，
  - 第二行是问题代码所在的包和函数，
  - 第三行是问题代码的具体位置，
  - 最后一行则是程序的退出状态

``` go
package main

import "fmt"

func main() {
    defer func() {
        fmt.Println("代码清理逻辑")
    }()

    var i = 1
    var j = 0
    if j == 0 {
        panic("除数不能为0！")
    }
    k := i / j
    fmt.Printf("%d / %d = %d\n", i, j, k)
}
```
![](panic1.png)

# recover() 函数
通过 recover() 函数对 panic 进行捕获和处理，<font color="red">从而避免程序崩溃然后直接退出</font>，而是继续可以执行后续代码，实现类似PHP 中 try...catch 语句的功能。
- 这个 panic 的捕获应该<font color="red">放到 defer 语句中</font>完成，才可以在抛出 panic 时通过 recover 函数将其捕获，**defer 语句执行完毕后，会退出抛出 panic 的当前函数**
``` go
defer func() {
    if err := recover(); err != nil {
        fmt.Printf("Runtime panic caught: %v\n", err)
    }
}()
```
- 通过 recover() 函数<font color="red">捕获了 panic，并打印捕获到的错误信息，这个时候，程序会退出函数而不是整个应用</font>
- 调用 defer 语句声明的匿名函数，如果没有panic发生，那么recover() 函数返回值为 nil，不会执行 if 分支代码
**类比为 panic、recover、defer 组合起来实现了传统面向对象编程异常处理的 try…catch…finally 功能。**
